language: php

sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=7a1ebaac44b17dbcc548f60761c7435fdcd5580e1583377588316462a49aac94

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

stages:
  - style
  - test
  - infection

jobs:
  include:
    - stage: Style

      php: 7.0

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate

      install:
        - composer install

      before_script:
        - mkdir -p $HOME/.php-cs-fixer

      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then COMMIT_RANGE=$TRAVIS_COMMIT_RANGE; else COMMIT_RANGE="HEAD~..HEAD"; fi;
        - CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")
        - if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then IFS=$'\n' EXTRA_ARGS=('--path-mode=intersection' '--' ${CHANGED_FILES[@]}); fi
        - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no "${EXTRA_ARGS[@]}"
        - vendor/bin/phpunit  --testsuite project

    - &TEST

      stage: Test

      php: 7.0

      env: WITH_LOCKED=true

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate

      install:
        - if [[ "$WITH_LOCKED" == "true" ]]; then composer install; fi
        - if [[ "$WITH_HIGHEST" == "true" ]]; then composer update; fi

      before_script:
        - source .travis/code-climate.sh
        - if [[ "$WITH_COVERAGE" == "true" ]]; then code-climate-before-script; fi

      script:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --testsuite unit; else vendor/bin/phpunit --testsuite unit; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi

      after_script:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then code-climate-after-script; fi

    - <<: *TEST

      php: 7.0

      env: WITH_HIGHEST=true

    - <<: *TEST

      php: 7.1

      env: WITH_LOCKED=true WITH_COVERAGE=true

    - <<: *TEST

      php: 7.1

      env: WITH_HIGHEST=true

    - <<: *TEST

      php: 7.2

      env: WITH_LOCKED=true

    - <<: *TEST

      php: 7.2

      env: WITH_HIGHEST=true

    - stage: Infection

      php: 7.1

      install:
        - composer install

      script:
        - vendor/bin/infection --min-msi=75
